### PR TITLE
populate ship names from key filename

### PR DESCRIPTION
**Pull request by neonfuz**
Implements https://github.com/Native-Planet/GroundSeg/issues/596

### CODE REVIEW

**Comment by nallux-dozryl** [comment]
I found two things:

- This doesn't work with keyfiles from bridge because bridge keyfiles has a `-n` at the end of the filename.
- Replacing a keyfile with another keyfile doesn't update the patp displayed

**Comment by neonfuz** [comment]
Good points. I wasn't aware of the first one, and I put code so that the population wouldn't clobber a user entered name, but tbh clobbering is probably fine. Should be very rare that someone wants to upload a ship with a different urbit valid name

**Comment by neonfuz** [comment]
@nallux-dozryl can you give an example of a bridge name? is it like sampel-palnet-n.key ?

**Comment by neonfuz** [comment]
Are there any other clients which hand out keys in weird formats that are known?

**Comment by nallux-dozryl** [comment]
@neonfuz my apologies, should've been clearer. Bridge's keyfile name is `<your @p>-<Network Key revision number>.key`. Eg: nallux-dozryl-3.key

> Are there any other clients which hand out keys in weird formats that are known?
not that I know of

**Comment by neonfuz** [comment]
I pushed fixes but am busy for the next few hours so I don't have time to test them

**Comment by neonfuz** [comment]
@nallux-dozryl Pushed another fix and tested, ready to merge again

**Pull request merged**
